### PR TITLE
Refactor slightly so Firefox updates the page in a more timely manner.

### PR DESCRIPTION
**Pull request by greggman**
The old way the tests were all using a bunch of setTimeout of 1ms.
    For whatever reason FF never processed the page in that case.

```
This patch restructures the code so each set of tests is run
and then we wait 100ms to give the browser a chance to show
the results before moving to the next test.
```

Hopefully this the last pull request for a while. 

Thanks for putting this together. Lots of people are looking at it.

### CODE REVIEW

**Comment by stepheneb** [comment]
Greg, How are you calculating the averages?

On Minefield Nightly I get these values for glMatrix and closure while the reported averages are glMatrix: 5.0 and closure: 3.7. 

```
           glMatrix   closure
----------------------------------
average    5.55       5.54
           8.00       7.20
           2.50       2.40
           2.10       4.00
           9.90       10.40
           9.10       10.70
           2.70       2.20
           5.40       7.50
           4.70       2.70
                      2.80
```

**Comment by greggman** [comment]
I haven't touched the average code.

I'll take a look though

**Comment by stepheneb** [comment]
Thanks, I'm going to bed now -- I'll check back tomorrow morning.

fyi: this is what I've been working on today while you improved the webgl matrix benchmarks ;-)

http://visual-demos.dev.concord.org/seasons/earth/seasons4.html

**Comment by stepheneb** [comment]
There's a problem in these changes. The Test no longer runs in Safari 5.0.5 or FireFox 3.6.15. Previous to merging this pull request glMatrix completed in both those browsers. It's a nice feature of glMatrix that it runs with both Typed and regular Arrays. I'd like to see more of the libraries do this.

**Comment by greggman** [comment]
Yea, ok, but the page says right on it, math libraries for WebGL.

WebGL doesn't run in Safari or FF 3.6

**Comment by stepheneb** [comment]
The fact that glMatrix also runs without using Typed Arrays is a big plus and getting a sense of it's speed is useful.

**Comment by stepheneb** [comment]
It's this commit that causes the glMatrix tests to not complete (or not get entered into the table) when running in Safari 5.0.5.
https://github.com/greggman/webgl-matrix-benchmarks/commit/5fd0acf1531c7f8c0d86019ad58a53c9a430fc36

I've looked at it but it's not clear to me why the fact that mjs throws an error when it is called the second time through this loop causes a different flow of execution than the code in the previous commit:

https://github.com/greggman/webgl-matrix-benchmarks/blob/5fd0acf1531c7f8c0d86019ad58a53c9a430fc36/matrix_benchmark.html#L125

**Comment by greggman** [comment]
Here's the problem.

The some libraries are NOT compatible with browsers that don't have
TypedArrays. The only reason it was working before was pure luck.

The only reason EWGL was working at all period is because mjs was defining
WebGLFloatArray as Float32Array since WebGLFloatArray no longer exists in
any browser. Remove mjs and EWGL stops working.

If mjs stops overriding Float32Array then Float32Array TDLFast overrides it
but it's just trying to make sure IE doesn't get an error when it reads the
JavaScript and assumes the app will not run.

Then, closure also stubs out Float32Array if it's not defined for exactly
the same reason as TDLFast does but then closure overrides Float32Array will
a full JavaScript implementation. Meaning that instead of just using Array
it make a class that emluates Float32Array including things like
BYTES_PER_ELEMENT, Float32Array.set and the different constructors.

If you let closure override Float32Array then the other libraries will work
but they'll work because they are using closures's emulation which means you
are not testing the correct thing.

To get it all to work requires
*) modifying mjs so it doesn't override Float32Array
*) modifying mjs so it switches between Float32Array and Array at runtime
*) modifying TDLFash so it doesn't override Float32Array
*) modifying closure so doesn't override Float32Array
*) Fixing EWGL so it uses Float32Array instead of WebGLFloatArray
*) making the benchmark skip EWGL, TDLFast, Closure
*) fixing tablesort.js because it requires the first column to not be empty
(more luck)

I have a patch that does this but seems like it's not the right thing to do
to me. Especially since if you update any of the libraries you'll have to
re-apply all these fixes.

Plus there's a new problem with that patch. At least on my I7 macbook pro
Safari is not fast enough to run the tests without popping up a "Script not
responding" dialog. To fix that requires a big refactoring to make it run
iteration of each test of each set in a separate setTimeout. Right now it's
running 8 libraries \* 10 iterations \* 50k tests for each setTimeout which is
just too much for a slow machine or a slow browser. And, given how fast it
runs on fast browsers and a fast machine we need to up that to 100k or 200k.
Right now, at least on my work machines some of the libraries are timed at
1-2ms which is too small to be accurate  and each time I run it a different
lib wins certain tests.

So, for now it's better to just change the page so it checks if typedarrays
exist and prints a mesasge 'You need a browser with typedarrays'

The other thing you could so is make something more like the
WebGL-Conformance-Test harness which runs each test in an iframe. Then they
wouldn't effect each other. That would mean each library would run in
isolation, no stepping on each other's toes. It also means you could run
Closure in browsers without typedarrays. That's probably a much better way
to do it but that's a big change.

https://cvs.khronos.org/svn/repos/registry/trunk/public/webgl/sdk/tests/webgl-conformance-tests.html

**Comment by stepheneb** [comment]
Thanks for doing that research. 

I agree that this benchmark should only test libraries using typed arrays.If I want to see the performance of the subset of libraries that also work with regular arrays I can make a similar page to do just that.

In regard to the effect the libraries have on each other -- I don't want to have to patch the libraries when updating them. It seems the only way to test them properly so things like re-definitions of Float32Array don't cause trouble is to run each lib  in an iFrame. Like you say however that's a larger change.

How much confidence do you have right now in the numeric results (with respect to the issue of how one library is affecting another)?

If this is affecting the comparative results to a degree that matters and there are simple patches to specific libraries that will make the current results more accurate then I think it makes sense to patch them now and then take a look at running the tests in an iFrame.

**Pull request merged**
