### PR TITLE
Switch to iterations per second.

### PR DESCRIPTION
**Pull request by greggman**
The advantage to this way is it's a step on the direction to
not timing out on any browser. Each test is only given
a certain amount of time to run.

The old way had the problem of setting the iteration count
too low meant the timing values were useless for fast machines
and fast browsers. Set it too high and it would timeout on
slow machines or slow browsers.

### CODE REVIEW

**Comment by stepheneb** [comment]
Thanks Gregg,

I changed the units to millions of iterations per second and merged the master branch into gh-pages
https://github.com/stepheneb/webgl-matrix-benchmarks/commit/969664d766b0087756b58ebbcba5a4029a69ec09

Don't know why  but the flotr graph doesn't appear in 13.0.782.3 canary on my Mac -- no JavaScript error in the console.

**Comment by greggman** [comment]
It works for me in 13.0.783.0.  You can download the absolute scary latest build here.

http://build.chromium.org/f/chromium/continuous/mac/LATEST/

**Comment by stepheneb** [comment]
Graph renders for me in 14.0.784.0 (87754) -- but not in 13.0.782.4 canary on Mac OS X.

**Comment by greggman** [comment]
Thanks for trying that. Will migrate the fixes from 14 back to 13 asap.

-gregg

**Pull request merged**
